// <auto-generated />
using System;
using FilmManagment.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FilmManagment.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200322114058_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FilmManagment.DAL.Entities.ActorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("FirstName");

                    b.Property<string>("PhotoFilePath");

                    b.Property<string>("SecondName");

                    b.Property<string>("WikiUrl");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("63156919-53f4-4a7a-b099-1c57bace2307"),
                            Age = 40,
                            FirstName = "John",
                            PhotoFilePath = "c:/blabla/nic/bla",
                            SecondName = "Stone",
                            WikiUrl = "wikiurl"
                        });
                });

            modelBuilder.Entity("FilmManagment.DAL.Entities.DirectorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("FirstName");

                    b.Property<string>("PhotoFilePath");

                    b.Property<string>("SecondName");

                    b.Property<string>("WikiUrl");

                    b.HasKey("Id");

                    b.ToTable("Directors");
                });

            modelBuilder.Entity("FilmManagment.DAL.Entities.FilmActorEntity", b =>
                {
                    b.Property<Guid>("FilmId");

                    b.Property<Guid>("ActorId");

                    b.Property<Guid>("Id");

                    b.HasKey("FilmId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("FilmActorEntity");
                });

            modelBuilder.Entity("FilmManagment.DAL.Entities.FilmDirectorEntity", b =>
                {
                    b.Property<Guid>("FilmId");

                    b.Property<Guid>("DirectorId");

                    b.Property<Guid>("Id");

                    b.HasKey("FilmId", "DirectorId");

                    b.HasIndex("DirectorId");

                    b.ToTable("FilmDirectorEntity");
                });

            modelBuilder.Entity("FilmManagment.DAL.Entities.FilmEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CountryOfOrigin");

                    b.Property<string>("CzechName");

                    b.Property<string>("Description");

                    b.Property<int>("GenreOfFilm");

                    b.Property<string>("ImageFilePath");

                    b.Property<TimeSpan>("LengthInMinutes");

                    b.Property<string>("OriginalName");

                    b.HasKey("Id");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("FilmManagment.DAL.Entities.RatingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("FilmId");

                    b.Property<int>("RatingInPercents");

                    b.Property<string>("TextRating");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("FilmManagment.DAL.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("FirstName");

                    b.Property<string>("NickName");

                    b.Property<string>("Password");

                    b.Property<string>("SecondName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FilmManagment.DAL.Entities.FilmActorEntity", b =>
                {
                    b.HasOne("FilmManagment.DAL.Entities.ActorEntity", "Actor")
                        .WithMany("ActedMovies")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FilmManagment.DAL.Entities.FilmEntity", "Film")
                        .WithMany("Actors")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FilmManagment.DAL.Entities.FilmDirectorEntity", b =>
                {
                    b.HasOne("FilmManagment.DAL.Entities.DirectorEntity", "Director")
                        .WithMany("DirectedMovies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FilmManagment.DAL.Entities.FilmEntity", "Film")
                        .WithMany("Directors")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FilmManagment.DAL.Entities.RatingEntity", b =>
                {
                    b.HasOne("FilmManagment.DAL.Entities.FilmEntity", "Film")
                        .WithMany("Ratings")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
